# Generated by Django 4.2 on 2024-09-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0004_restaurant_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="写真"
            ),
        ),
    ]
