# Generated by Django 4.2.16 on 2024-10-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0006_restaurant_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reservation_time",
            field=models.TimeField(default="", verbose_name="時刻"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateField(verbose_name="予約日"),
        ),
    ]
