# Generated by Django 4.2.16 on 2024-10-06 01:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0007_reservation_reservation_time_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="reservation_time",
            field=models.TimeField(verbose_name="時刻"),
        ),
    ]
