# Generated by Django 4.2.16 on 2024-10-06 01:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0008_alter_reservation_reservation_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="reservation_time",
        ),
    ]
