# Generated by Django 4.2.16 on 2024-10-06 01:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0009_remove_reservation_reservation_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reservation_time",
            field=models.TimeField(default="18:00", verbose_name="時刻"),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateTimeField(verbose_name="予約日"),
        ),
    ]
