# Generated by Django 4.2.16 on 2024-10-06 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0011_remove_reservation_reservation_date_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservation",
            name="unique_reservation",
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "user", "date", "time"), name="unique_reservation"
            ),
        ),
    ]
