# Generated by Django 4.2 on 2024-09-09 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_job_alter_customuser_job"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="accounts.job",
            ),
        ),
    ]
