# Generated by Django 4.2.16 on 2024-10-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_alter_customuser_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="created_day",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="登録日"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="deleted_day",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="削除日"
            ),
        ),
        migrations.AddField(
            model_name="customuser",
            name="updated_day",
            field=models.DateTimeField(
                auto_now_add=True, null=True, verbose_name="更新日"
            ),
        ),
    ]
