# Generated by Django 4.2.16 on 2024-10-13 00:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_customuser_created_day_customuser_deleted_day_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="created_day",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True, verbose_name="登録日"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="deleted_day",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True, verbose_name="削除日"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="updated_day",
            field=models.DateTimeField(
                blank=True, default=datetime.datetime.now, null=True, verbose_name="更新日"
            ),
        ),
    ]
