# Generated by Django 4.2.16 on 2024-10-22 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_customuser_deleted_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="MonthlySales",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateTimeField(blank=True, null=True, verbose_name="年月日"),
                ),
                (
                    "sales",
                    models.IntegerField(blank=True, null=True, verbose_name="売上"),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="monthlysales",
            constraint=models.UniqueConstraint(fields=("date",), name="unique_date"),
        ),
    ]
