# Generated by Django 4.2.16 on 2024-11-23 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        (
            "accounts",
            "0008_customuser_regist_date_customuser_stripecustomerid_and_more",
        ),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="stripeCustomerId",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="stripeSubscriptionId",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="job",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="accounts.job",
            ),
        ),
    ]
