# Generated by Django 4.2.16 on 2024-10-06 01:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservation",
            name="unique_reservation",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="reservation_time",
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "user", "reservation_date"),
                name="unique_reservation",
            ),
        ),
    ]
