# Generated by Django 4.2.16 on 2024-10-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0002_remove_reservation_unique_reservation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="reservation_time",
            field=models.TimeField(
                blank=True, default="18:00", null=True, verbose_name="時刻"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="visited_at",
            field=models.DateField(blank=True, null=True, verbose_name="利用日"),
        ),
    ]
