# Generated by Django 4.2 on 2024-09-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0005_category_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="", verbose_name="写真"
            ),
        ),
    ]
