# Generated by Django 4.2.16 on 2024-10-06 01:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="date",
        ),
        migrations.RemoveField(
            model_name="reservation",
            name="time",
        ),
        migrations.AddField(
            model_name="reservation",
            name="reservation_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="予約日"),
        ),
        migrations.AddField(
            model_name="reservation",
            name="reservation_time",
            field=models.TimeField(
                blank=True, default="18:00", null=True, verbose_name="時刻"
            ),
        ),
    ]
