# Generated by Django 4.2.16 on 2024-10-06 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("restaurant", "0003_remove_reservation_unique_reservation_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="reservation",
            name="unique_reservation",
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                fields=("restaurant", "user", "reservation_date", "reservation_time"),
                name="unique_reservation",
            ),
        ),
    ]
